<?php

namespace zxp\simditor;

use Yii;
use yii\base\Action;
use yii\helpers\ArrayHelper;
use yii\web\Response;
use yii\web\UploadedFile;

class SimditorAction extends Action
{
    public $config = [];

    public function init()
    {
        $_config = [
            'uploadDir' => Yii::getAlias('@webroot')
        ];
        $this->config = ArrayHelper::merge($_config, $this->config);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionUpload()
    {
    }

    public function run()
    {
        if (Yii::$app->request->get('callback',false)) {
            Yii::$app->response->format = Response::FORMAT_JSONP;
        } else {
            Yii::$app->response->format = Response::FORMAT_JSON;
        }
        return $this->handleAction();
    }

    protected function handleAction()
    {
        $action = Yii::$app->request->get('action');
        switch ($action) {
            case 'upload':
                $result = $this->actionUpload();
                $result['url'] = Yii::getAlias('@web'.$result['url']);
                break;
            default:
                break;
        }
    }
}