<?php

namespace zxp\simditor;

use yii\base\Model;
use yii\base\Widget;
use yii\helpers\Html;
use yii\web\JsExpression;

class Simditor extends Widget
{
    public $model;

    public $attribute;

    public $name;

    public $options = [];

    public $clientOptions =[];

    public function init()
    {
        if (!isset($this->options['id'])) {
            $this->options['id'] = $this->hasModel() ? Html::getInputId($this->model, $this->attribute) : $this->getId();
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if ($this->hasModel()) {
            echo Html::activeTextarea($this->model, $this->attribute, $this->options);
        } else {
            echo Html::textarea($this->name, '',$this->options);
        }
    }

    protected function registerPlugin()
    {
        $cleanOptions = $this->getClientOptions();
        $js = "var editor=new Simditor($cleanOptions);";
        $this->view->registerJs($js, View::POS_READY);
    }

    protected function getClientOptions()
    {
        $id = $this->options['id'];
        $options['textarea'] = new JsExpression("$('#{$id}')");
        $options = array_merge($options, $this->options);
        return Json::encode($options);
    }

    protected function hasModel()
    {
        return $this->model instanceof Model && $this->attribute !== null;
    }
}
